-------------------------------------------------------------------------------
-- Title      : Components package (generated by Emacs VHDL Mode 3.38.1)
-- Project    :
-------------------------------------------------------------------------------
-- File       : components.vhd
-- Author     : Nico De Simone  <nico.desimone@desy.de>
-- Company    : DESY
-- Created    : 2023-05-31
-- Last update: 2026-05-20
-- Platform   :
-- Standard   : VHDL'08
-------------------------------------------------------------------------------
-- Description:
-------------------------------------------------------------------------------
-- Copyright (c) 2023 DESY
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author  Description
-- 2023-05-31  1.0      desimone    Created
-------------------------------------------------------------------------------

library ieee;
context ieee.ieee_std_context;

package components_helper is

      function ceil_log(n, b : positive) return natural;
      function ceil_log2(n   : positive) return natural;

end package components_helper;

package body components_helper is

      --## Compute the integer result of the function ceil(log(n)) where b is the base.
      function ceil_log(n, b : positive) return natural is
            variable log, residual : natural;
      begin

            residual := n - 1;
            log      := 0;

            while residual > 0 loop
                  residual := residual / b;
                  log      := log + 1;
            end loop;

            return log;
      end function;

      --## Compute the integer result of the function ceil(log2(n)).
      function ceil_log2(n : positive) return natural is
      begin
            return ceil_log(n, 2);
      end function;

end package body components_helper;

library ieee;
context ieee.ieee_std_context;
use work.components_helper.all;

package components is

      -----------------------------------------------------------------------------
      -- Component declarations
      -----------------------------------------------------------------------------

      component axis_fifo is
            generic (
                  DEPTH                : integer := 4096;
                  DATA_WIDTH           : integer := 8;
                  KEEP_ENABLE          : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH           : integer := ((DATA_WIDTH+7)/8);
                  LAST_ENABLE          : boolean := true;
                  ID_ENABLE            : boolean := false;
                  ID_WIDTH             : integer := 8;
                  DEST_ENABLE          : boolean := false;
                  DEST_WIDTH           : integer := 8;
                  USER_ENABLE          : boolean := true;
                  USER_WIDTH           : integer := 1;
                  RAM_PIPELINE         : integer := 1;
                  OUTPUT_FIFO_ENABLE   : boolean := false;
                  FRAME_FIFO           : boolean := false;
                  USER_BAD_FRAME_VALUE : boolean := true;
                  USER_BAD_FRAME_MASK  : integer := 1;
                  DROP_OVERSIZE_FRAME  : boolean := FRAME_FIFO;
                  DROP_BAD_FRAME       : boolean := false;
                  DROP_WHEN_FULL       : boolean := false;
                  MARK_WHEN_FULL       : boolean := false;
                  PAUSE_ENABLE         : boolean := false;
                  FRAME_PAUSE          : boolean := FRAME_FIFO
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0);

                  pause_req : in  std_ulogic;
                  pause_ack : out std_ulogic;

                  status_depth        : out std_ulogic_vector(ceil_log2(DEPTH) downto 0);
                  status_depth_commit : out std_ulogic_vector(ceil_log2(DEPTH) downto 0);
                  status_overflow     : out std_logic;
                  status_bad_frame    : out std_logic;
                  status_good_frame   : out std_logic);
      end component axis_fifo;

      component axis_register is
            generic (
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  LAST_ENABLE : boolean := true;
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1;
                  REG_TYPE    : integer := 2);
            port (
                  clk           : in  std_logic;
                  rst           : in  std_logic;
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);
                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0));
      end component axis_register;

      component axis_srl_register is
            generic (
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  LAST_ENABLE : boolean := true;
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1);
            port (
                  clk           : in  std_logic;
                  rst           : in  std_logic;
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);
                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0));
      end component axis_srl_register;

      component axis_pipeline_register is
            generic (
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  LAST_ENABLE : boolean := true;
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1;
                  REG_TYPE    : integer := 2;
                  LENGTH      : integer := 2
                  );
            port (
                  clk           : in  std_logic;
                  rst           : in  std_logic;
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);
                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0));
      end component axis_pipeline_register;

      component axis_srl_fifo is
            generic (
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  LAST_ENABLE : boolean := true;
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1;
                  DEPTH       : integer := 16
                  );
            port (
                  clk           : in  std_logic;
                  rst           : in  std_logic;
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);
                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0);
                  count         : out std_ulogic_vector(ceil_log2(DEPTH+1)-1 downto 0));
      end component axis_srl_fifo;

      component axis_adapter is
            generic (
                  S_DATA_WIDTH  : integer := 8;
                  S_KEEP_ENABLE : boolean := (S_DATA_WIDTH > 8);
                  S_KEEP_WIDTH  : integer := ((S_DATA_WIDTH+7)/8);
                  M_DATA_WIDTH  : integer := 8;
                  M_KEEP_ENABLE : boolean := (M_DATA_WIDTH > 8);
                  M_KEEP_WIDTH  : integer := ((M_DATA_WIDTH+7)/8);
                  ID_ENABLE     : boolean := false;
                  ID_WIDTH      : integer := 8;
                  DEST_ENABLE   : boolean := false;
                  DEST_WIDTH    : integer := 8;
                  USER_ENABLE   : boolean := true;
                  USER_WIDTH    : integer := 1);
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(S_DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(S_KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(M_DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(M_KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0));
      end component axis_adapter;

      component axis_mux is
            generic (
                  S_COUNT     : integer := 4;
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1);
            port (
                  clk : in std_ulogic;
                  rst : in std_ulogic;

                  s_axis_tdata  : in  std_ulogic_vector(S_COUNT*DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(S_COUNT*KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tready : out std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tlast  : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tid    : in  std_ulogic_vector(S_COUNT*ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(S_COUNT*DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(S_COUNT*USER_WIDTH-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0);

                  enable : in std_ulogic;
                  sel    : in std_ulogic_vector(ceil_log2(S_COUNT)-1 downto 0)
                  );
      end component axis_mux;

      component axis_arb_mux is
            generic (
                  S_COUNT               : integer := 4;
                  DATA_WIDTH            : integer := 8;
                  KEEP_ENABLE           : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH            : integer := ((DATA_WIDTH+7)/8);
                  ID_ENABLE             : boolean := false;
                  S_ID_WIDTH            : integer := 8;
                  M_ID_WIDTH            : integer := S_ID_WIDTH+ceil_log2(S_COUNT);
                  DEST_ENABLE           : boolean := false;
                  DEST_WIDTH            : integer := 8;
                  USER_ENABLE           : boolean := true;
                  USER_WIDTH            : integer := 1;
                  LAST_ENABLE           : boolean := true;
                  UPDATE_TID            : boolean := false;
                  ARB_TYPE_ROUND_ROBIN  : boolean := false;
                  ARB_LSB_HIGH_PRIORITY : boolean := true
                  );
            port (
                  clk : in std_ulogic;
                  rst : in std_ulogic;

                  s_axis_tdata  : in  std_ulogic_vector(S_COUNT*DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(S_COUNT*KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tready : out std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tlast  : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tid    : in  std_ulogic_vector(S_COUNT*S_ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(S_COUNT*DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(S_COUNT*USER_WIDTH-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tid    : out std_ulogic_vector(M_ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0)
                  );
      end component axis_arb_mux;

      component axis_frame_join is
            generic (
                  S_COUNT    : integer := 4;
                  DATA_WIDTH : integer := 8;
                  TAG_ENABLE : boolean := true;
                  TAG_WIDTH  : integer := DATA_WIDTH
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(S_COUNT*DATA_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tready : out std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tlast  : in  std_ulogic_vector(S_COUNT-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(S_COUNT-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tuser  : out std_logic;

                  tag  : in  std_ulogic_vector(TAG_WIDTH-1 downto 0);
                  busy : out std_logic
                  );
      end component axis_frame_join;

      component axis_cobs_decode is
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(7 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tuser  : in  std_ulogic;

                  m_axis_tdata  : out std_ulogic_vector(7 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tuser  : out std_ulogic
                  );
      end component axis_cobs_decode;

      component axis_cobs_encode is
            generic (
                  APPEND_ZERO : boolean := true
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(7 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tuser  : in  std_ulogic;

                  m_axis_tdata  : out std_ulogic_vector(7 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tuser  : out std_ulogic
                  );
      end component axis_cobs_encode;

      component axis_frame_length_adjust is
            generic (
                  DATA_WIDTH  : integer := 8;
                  KEEP_ENABLE : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH  : integer := ((DATA_WIDTH+7)/8);
                  ID_ENABLE   : boolean := false;
                  ID_WIDTH    : integer := 8;
                  DEST_ENABLE : boolean := false;
                  DEST_WIDTH  : integer := 8;
                  USER_ENABLE : boolean := true;
                  USER_WIDTH  : integer := 1);
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  m_axis_tdata  : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic;
                  m_axis_tready : in  std_ulogic;
                  m_axis_tlast  : out std_ulogic;
                  m_axis_tid    : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(USER_WIDTH-1 downto 0);

                  status_valid                 : out std_ulogic;
                  status_ready                 : in  std_ulogic;
                  status_frame_pad             : out std_ulogic;
                  status_frame_truncate        : out std_ulogic;
                  status_frame_length          : out unsigned(15 downto 0);
                  status_frame_original_length : out unsigned(15 downto 0);

                  length_min : in unsigned(15 downto 0);
                  length_max : in unsigned(15 downto 0)
                  );
      end component axis_frame_length_adjust;

      component axis_frame_length_adjust_fifo is
            generic (
                  DATA_WIDTH        : integer := 8;
                  KEEP_ENABLE       : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH        : integer := ((DATA_WIDTH+7)/8);
                  ID_ENABLE         : boolean := false;
                  ID_WIDTH          : integer := 8;
                  DEST_ENABLE       : boolean := false;
                  DEST_WIDTH        : integer := 8;
                  USER_ENABLE       : boolean := true;
                  USER_WIDTH        : integer := 1;
                  FRAME_FIFO_DEPTH  : integer := 4096;
                  HEADER_FIFO_DEPTH : integer := 8);
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  m_axis_hdr_valid           : out std_ulogic;
                  m_axis_hdr_ready           : in  std_ulogic;
                  m_axis_hdr_pad             : out std_ulogic;
                  m_axis_hdr_truncate        : out std_ulogic;
                  m_axis_hdr_length          : out unsigned(15 downto 0);
                  m_axis_hdr_original_length : out unsigned(15 downto 0);
                  m_axis_tdata               : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep               : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid              : out std_ulogic;
                  m_axis_tready              : in  std_ulogic;
                  m_axis_tlast               : out std_ulogic;
                  m_axis_tid                 : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest               : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser               : out std_ulogic_vector(USER_WIDTH-1 downto 0);

                  length_min : in unsigned(15 downto 0);
                  length_max : in unsigned(15 downto 0)
                  );
      end component axis_frame_length_adjust_fifo;

      component axis_tap is
            generic (
                  DATA_WIDTH           : integer := 8;
                  KEEP_ENABLE          : boolean := (DATA_WIDTH > 8);
                  KEEP_WIDTH           : integer := ((DATA_WIDTH+7)/8);
                  ID_ENABLE            : boolean := false;
                  ID_WIDTH             : integer := 8;
                  DEST_ENABLE          : boolean := false;
                  DEST_WIDTH           : integer := 8;
                  USER_ENABLE          : boolean := true;
                  USER_WIDTH           : integer := 1;
                  USER_BAD_FRAME_VALUE : integer := 1;
                  USER_BAD_FRAME_MASK  : integer := 1);
            port (
                  clk             : in  std_logic;
                  rst             : in  std_logic;
                  tap_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  tap_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  tap_axis_tvalid : in  std_logic;
                  tap_axis_tready : in  std_logic;
                  tap_axis_tlast  : in  std_logic;
                  tap_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  tap_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  tap_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);
                  m_axis_tdata    : out std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  m_axis_tkeep    : out std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid   : out std_logic;
                  m_axis_tready   : in  std_logic;
                  m_axis_tlast    : out std_logic;
                  m_axis_tid      : out std_ulogic_vector(ID_WIDTH-1 downto 0);
                  m_axis_tdest    : out std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  m_axis_tuser    : out std_ulogic_vector(USER_WIDTH-1 downto 0));
      end component axis_tap;

      component axis_demux is
            generic (
                  -- Number of AXI stream outputs
                  M_COUNT      : positive := 4;
                  -- Width of AXI stream interfaces in bits
                  DATA_WIDTH   : positive := 8;
                  -- Propagate tkeep signal
                  KEEP_ENABLE  : boolean  := (DATA_WIDTH > 8);
                  -- tkeep signal width (bytes per cycle)
                  KEEP_WIDTH   : positive := (DATA_WIDTH + 7) / 8;
                  -- Propagate tid signal
                  ID_ENABLE    : boolean  := false;
                  -- tid signal width
                  ID_WIDTH     : positive := 8;
                  -- Propagate tdest signal
                  DEST_ENABLE  : boolean  := false;
                  -- output tdest signal width
                  M_DEST_WIDTH : positive := 8;
                  -- input tdest signal width
                  S_DEST_WIDTH : positive := M_DEST_WIDTH + ceil_log2(M_COUNT);
                  -- Propagate tuser signal
                  USER_ENABLE  : boolean  := true;
                  -- tuser signal width
                  USER_WIDTH   : positive := 1;
                  -- Route via tdest
                  TDEST_ROUTE  : boolean  := false
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  ---------------------------------------------------------------------
                  -- AXI input
                  ---------------------------------------------------------------------
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic;
                  s_axis_tready : out std_logic;
                  s_axis_tlast  : in  std_logic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(S_DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  ---------------------------------------------------------------------
                  -- AXI outputs (flattened, packed by M_COUNT)
                  ---------------------------------------------------------------------
                  m_axis_tdata  : out std_ulogic_vector(M_COUNT*DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(M_COUNT*KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tready : in  std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tlast  : out std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tid    : out std_ulogic_vector(M_COUNT*ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(M_COUNT*M_DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(M_COUNT*USER_WIDTH-1 downto 0);

                  ---------------------------------------------------------------------
                  -- Control
                  ---------------------------------------------------------------------
                  enable : in std_logic;
                  drop   : in std_logic;
                  sel    : in std_ulogic_vector(ceil_log2(M_COUNT)-1 downto 0)
                  );
      end component axis_demux;

      component axis_broadcast is
            generic (
                  -- Number of AXI stream outputs
                  M_COUNT     : positive := 4;
                  -- Width of AXI stream interfaces in bits
                  DATA_WIDTH  : positive := 8;
                  -- Propagate tkeep signal
                  KEEP_ENABLE : boolean  := (DATA_WIDTH > 8);
                  -- tkeep signal width (words per cycle)
                  KEEP_WIDTH  : positive := (DATA_WIDTH + 7) / 8;
                  -- Propagate tlast signal
                  LAST_ENABLE : boolean  := true;
                  -- Propagate tid signal
                  ID_ENABLE   : boolean  := false;
                  -- tid signal width
                  ID_WIDTH    : positive := 8;
                  -- Propagate tdest signal
                  DEST_ENABLE : boolean  := false;
                  -- tdest signal width
                  DEST_WIDTH  : positive := 8;
                  -- Propagate tuser signal
                  USER_ENABLE : boolean  := true;
                  -- tuser signal width
                  USER_WIDTH  : positive := 1
                  );
            port (
                  clk : in std_ulogic;
                  rst : in std_ulogic;

                  -- AXI input
                  s_axis_tdata  : in  std_ulogic_vector(DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_ulogic_vector(KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_ulogic;
                  s_axis_tready : out std_ulogic;
                  s_axis_tlast  : in  std_ulogic;
                  s_axis_tid    : in  std_ulogic_vector(ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_ulogic_vector(DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_ulogic_vector(USER_WIDTH-1 downto 0);

                  -- AXI outputs (flattened)
                  m_axis_tdata  : out std_ulogic_vector(M_COUNT*DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_ulogic_vector(M_COUNT*KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tready : in  std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tlast  : out std_ulogic_vector(M_COUNT-1 downto 0);
                  m_axis_tid    : out std_ulogic_vector(M_COUNT*ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_ulogic_vector(M_COUNT*DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_ulogic_vector(M_COUNT*USER_WIDTH-1 downto 0)
                  );
      end component axis_broadcast;

      component axis_switch
            generic (
                  -- Number of AXI stream inputs
                  S_COUNT               : integer := 4;
                  -- Number of AXI stream outputs
                  M_COUNT               : integer := 4;
                  -- Width of AXI stream interfaces in bits
                  DATA_WIDTH            : integer := 8;
                  -- Propagate tkeep signal
                  KEEP_ENABLE           : integer := 1;
                  -- tkeep signal width
                  KEEP_WIDTH            : integer := 1;
                  -- Propagate tid
                  ID_ENABLE             : integer := 0;
                  -- input tid width
                  S_ID_WIDTH            : integer := 8;
                  -- output tid width
                  M_ID_WIDTH            : integer := 8;
                  -- output tdest width
                  M_DEST_WIDTH          : integer := 1;
                  -- input tdest width
                  S_DEST_WIDTH          : integer := 2;
                  -- propagate tuser
                  USER_ENABLE           : integer := 1;
                  -- user width
                  USER_WIDTH            : integer := 1;
                  -- routing base/top
                  M_BASE                : integer := 0;
                  M_TOP                 : integer := 0;
                  -- M_COUNT groups of S_COUNT bits
                  M_CONNECT             : integer := 0;
                  -- update TID
                  UPDATE_TID            : integer := 0;
                  -- input/output register types
                  S_REG_TYPE            : integer := 0;
                  M_REG_TYPE            : integer := 2;
                  -- arbitration
                  ARB_TYPE_ROUND_ROBIN  : integer := 1;
                  ARB_LSB_HIGH_PRIORITY : integer := 1
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  -- AXI Stream inputs
                  s_axis_tdata  : in  std_logic_vector(S_COUNT*DATA_WIDTH-1 downto 0);
                  s_axis_tkeep  : in  std_logic_vector(S_COUNT*KEEP_WIDTH-1 downto 0);
                  s_axis_tvalid : in  std_logic_vector(S_COUNT-1 downto 0);
                  s_axis_tready : out std_logic_vector(S_COUNT-1 downto 0);
                  s_axis_tlast  : in  std_logic_vector(S_COUNT-1 downto 0);
                  s_axis_tid    : in  std_logic_vector(S_COUNT*S_ID_WIDTH-1 downto 0);
                  s_axis_tdest  : in  std_logic_vector(S_COUNT*S_DEST_WIDTH-1 downto 0);
                  s_axis_tuser  : in  std_logic_vector(S_COUNT*USER_WIDTH-1 downto 0);

                  -- AXI Stream outputs
                  m_axis_tdata  : out std_logic_vector(M_COUNT*DATA_WIDTH-1 downto 0);
                  m_axis_tkeep  : out std_logic_vector(M_COUNT*KEEP_WIDTH-1 downto 0);
                  m_axis_tvalid : out std_logic_vector(M_COUNT-1 downto 0);
                  m_axis_tready : in  std_logic_vector(M_COUNT-1 downto 0);
                  m_axis_tlast  : out std_logic_vector(M_COUNT-1 downto 0);
                  m_axis_tid    : out std_logic_vector(M_COUNT*M_ID_WIDTH-1 downto 0);
                  m_axis_tdest  : out std_logic_vector(M_COUNT*M_DEST_WIDTH-1 downto 0);
                  m_axis_tuser  : out std_logic_vector(M_COUNT*USER_WIDTH-1 downto 0)
                  );
      end component;

      component axis_stat_counter is
            generic (
                  -- Width of AXI stream interfaces in bits
                  DATA_WIDTH : integer := 64;
                  -- Propagate tkeep signal
                  -- If disabled, tkeep is assumed to be 1'b1
                  KEEP_ENABLE : boolean  := (DATA_WIDTH > 8);
                  -- tkeep signal width (words per cycle)
                  KEEP_WIDTH  : positive := (DATA_WIDTH + 7) / 8;
                  -- Prepend data with tag
                  TAG_ENABLE : boolean := true;
                  -- Tag field width
                  TAG_WIDTH : integer := 16;
                  -- Count cycles
                  TICK_COUNT_ENABLE : boolean := true;
                  -- Cycle counter width
                  TICK_COUNT_WIDTH : integer := 32;
                  -- Count bytes
                  BYTE_COUNT_ENABLE : boolean := true;
                  -- Byte counter width
                  BYTE_COUNT_WIDTH : integer := 32;
                  -- Count frames
                  FRAME_COUNT_ENABLE : boolean := true;
                  -- Frame counter width
                  FRAME_COUNT_WIDTH : integer := 32
                  );
            port (
                  clk : in std_logic;
                  rst : in std_logic;

                  ---------------------------------------------------------------------------
                  -- AXI monitor
                  ---------------------------------------------------------------------------
                  monitor_axis_tkeep  : in std_logic_vector(KEEP_WIDTH - 1 downto 0);
                  monitor_axis_tvalid : in std_logic;
                  monitor_axis_tready : in std_logic;
                  monitor_axis_tlast  : in std_logic;

                  ---------------------------------------------------------------------------
                  -- AXI status data output
                  ---------------------------------------------------------------------------
                  m_axis_tdata  : out std_logic_vector(7 downto 0);
                  m_axis_tvalid : out std_logic;
                  m_axis_tready : in  std_logic;
                  m_axis_tlast  : out std_logic;
                  m_axis_tuser  : out std_logic;

                  ---------------------------------------------------------------------------
                  -- Configuration
                  ---------------------------------------------------------------------------
                  tag     : in std_logic_vector(TAG_WIDTH - 1 downto 0);
                  trigger : in std_logic;

                  ---------------------------------------------------------------------------
                  -- Status
                  ---------------------------------------------------------------------------
                  busy : out std_logic
                  );
      end component axis_stat_counter;

end package components;
